[package]
name = "UI_ANDU_new"
version = "0.1.0"
edition = "2024"

[dependencies]
UI_ANDU_new_derive = { path = "UI_ANDU_new_derive" }
colored = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
